MySqlTestApplication/Models/DataPoint.cs
using System;
using System.Runtime.Serialization;

namespace MySqlTestApplication.Models
{
    [DataContract]
    public class DataPoint
    {
		public DataPoint(string label, decimal y)
        {
            this.Label = label;
            this.Y = y;
        }

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "label")]
        public string Label = "";

        //Explicitly setting the name to be used while serializing to JSON.
        [DataMember(Name = "y")]
        public Nullable<decimal> Y = null;
    }
}

MySqlTestApplication/Models/SplineChartModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MySqlTestApplication.Models
{
    public class SplineChartModel
    {
    }
}

MySqlTestApplication/Controllers/DateTimePickerController.cs
using System.Web.Mvc;

namespace MySqlTestApplication.Controllers
{
    public class DateTimePickerController : Controller
    {
        [HttpPost]
        public ActionResult SearchByDateInBetween()
        {
            HomeController homeController = new HomeController();
            return ViewBag;
        }
    }
}

MySqlTestApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Web.Mvc;
using MySql.Data.MySqlClient;
using MySqlTestApplication.Models;
using Newtonsoft.Json;

namespace MySqlTestApplication.Controllers
{
    public class HomeController : Controller
    {
        private MySqlConnection mySqlConnection;
        private string connectionString;

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Carbondioxide()
        {
            try
            {
                string query = "SELECT * FROM carbondioxide";
                SplineChart(query, "Carbondioxide");
            }
            catch (Exception e)
            {
                ViewBag.Message = "nope";
                Console.WriteLine(e);
                throw;
            }

            return View();
        }

        public ActionResult Humidity()
        {
            try
            {
                string query = "SELECT * FROM humidity";
                SplineChart(query, "Humidity");
            }
            catch (Exception e)
            {
                ViewBag.Message = "nope";
                Console.WriteLine(e);
                throw;
            }

            return View();
        }

        public ActionResult Temperature(string button)
        {
            try
            {
                string query = string.Empty;
                if (button == "buttonSearch")
                {
                    query = "SELECT * FROM temperature WHERE MeasuredDateTime between '2020-09-29 10:44:00' and '2020-09-29 11:00:50' ";
                }
                else
                {
                    query = "SELECT * FROM temperature";

                }
                SplineChart(query, "Temperature");
            }
            catch (Exception e)
            {
                ViewBag.Message = "nope";
                Console.WriteLine(e);
                throw;
            }

            return View();
        }

        private void SplineChart(string query, string attributeName)
        {
            DataTable dt = MySqlConnectionTest(query);
            List<DataPoint> dataPoints = new List<DataPoint>();
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                dataPoints.Add(new DataPoint( dt.Rows[i]["MeasuredDateTime"].ToString(), (decimal)dt.Rows[i][attributeName]));
            }

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
        }

        private DataTable MySqlConnectionTest(string query)
        {
            string connection = "SERVER= 127.0.0.1;PORT=3306;DATABASE=air_live;UID=root;PASSWORD=juventus";
            DataTable dataTable = new DataTable();

            try
            {
                mySqlConnection = new MySqlConnection();
                mySqlConnection.ConnectionString = connection;
                mySqlConnection.Open();

                MySqlCommand cmd = new MySqlCommand(query, mySqlConnection);
                MySqlDataReader dataReader = cmd.ExecuteReader();

                dataTable.Load(dataReader, LoadOption.OverwriteChanges);
                mySqlConnection.Close();
            }
            catch (MySqlException sqlException)
            {
                Console.WriteLine(sqlException);
                throw;
            }

            return dataTable;
        }
    }
}

MySqlTestApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

MySqlTestApplication/Views/Home/Carbondioxide.cshtml
@{
    ViewBag.Title = "Carbon Dioxide";
}

<!DOCTYPE HTML>
<html>
<head>
    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainerCarbonDioxide", {
                animationEnabled: true,
                title: {
                    text: "Carbon dioxide"
                },
                axisX: {
                    valueFormatString: "DD MMM"
                },
                axisY: {
                    title: "Atmospheric CO2",
                    valueFormatString: "#,##0.##"
                },
                data: [{
                    type: "spline",
                    xValueType: "dateTime",
                    xValueFormatString: "DD MMM",
                    yValueFormatString: "#,###.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
            });
            chart.render();

        }
    </script>
</head>
<body>
    <div id="chartContainerCarbonDioxide" class="default-chart"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html> 

MySqlTestApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
 
<!DOCTYPE HTML>
<html>
<head>
    <script>
        window.onload = function () {
 
            var chart = new CanvasJS.Chart("chartContainer", {
                animationEnabled: true,
                title: {
                    text: "Temperature"
                },
                axisX: {
                    valueFormatString: "DD MMM"
                },
                axisY: {
                    title: "Temperature in celsius ",
                    valueFormatString: "#,##0.##",
                    suffix: "°"
                },
                data: [{
                    type: "spline",
                    xValueType: "dateTime",
                    xValueFormatString: "DD MMM",
                    yValueFormatString: "#,###.##",					
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
            });
            chart.render();
 
        }
    </script>
</head>
<body>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>	
</body>
</html> 

MySqlTestApplication/Views/Home/Humidity.cshtml
@{
    ViewBag.Title = "Humidity";
}

<!DOCTYPE HTML>
<html>
<head>
    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainerHumidity", {
                animationEnabled: true,
                title: {
                    text: "Humidity"
                },
                axisX: {
                    valueFormatString: "DD MMM"
                },
                axisY: {
                    title: "Relative Humidity(%)",
                    valueFormatString: "#,##0.##"
                },
                data: [{
                    type: "spline",
                    xValueType: "dateTime",
                    xValueFormatString: "DD MMM",
                    yValueFormatString: "#,###.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
            });
            chart.render();

        }
    </script>
</head>
<body>
    <div id="chartContainerHumidity" class="default-chart"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html> 

MySqlTestApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MySqlTestApplication/Views/Home/Temperature.cshtml
@{
    ViewBag.Title = "Temperature";
}

<!DOCTYPE HTML>
<html>
<head>
    <script>
        window.onload = function () {

            var chart = new CanvasJS.Chart("chartContainerTemperature", {
                animationEnabled: true,
                title: {
                    text: "Temperature"
                },
                axisX: {
                    valueFormatString: "DD MMM"
                },
                axisY: {
                    title: "Temperature in celsius ",
                    valueFormatString: "#,##0.##",
                    suffix: "°"
                },
                data: [{
                    type: "spline",
                    xValueType: "dateTime",
                    xValueFormatString: "DD MMM",
                    yValueFormatString: "#,###.##",
                    dataPoints: @Html.Raw(ViewBag.DataPoints)
                }]
            });
            chart.render();

        }
    </script>
</head>
<body>

<div>
    <div class="row">
        <h1>CRUD implementieren</h1>
        <p>Datenpunkt erfassen, Datenpunkt editieren, Datenpunkt löschen</p>
        <div>
            @Html.Label("From", null, new {@class = "control-label col-xs-1 spline-chart-style"})
            <div class="col-xs-2">
                <input type="date"/>
            </div>
            @Html.Label("To", null, new {@class = "control-label col-xs-1 spline-chart-style"})
            <div class="col-xs-1">
                <input type="date"/>
            </div>
            <div class="col-xs-2">
                @using (Html.BeginForm("SearchByDateInBetween", "DateTimePicker"))
                {
                    <input type="button" name="buttonSearch" class="btn btn-primary" value="search"/>
                }
            </div>
        </div>
    </div>
</div>
<div id="chartContainerTemperature" class="default-chart"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
</body>
</html> 

MySqlTestApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Air life Analyzer</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"></button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Carbondioxide", "Carbondioxide", "Home")</li>
                    <li>@Html.ActionLink("Humidity", "Humidity", "Home")</li>
                    <li>@Html.ActionLink("Temperature", "Temperature", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="footer-copyright">&copy; @DateTime.Now.Year - Made by Joël Iselin & Roland Jaggi, for Software Engineering 3, Class: TS TSI 1809 A 05 SoE</p>
</footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>